dist: trusty
language: python
python:
  - "3.6"

before_install:
  - ./install.sh
  - export PATH=$PATH:$PWD/
  - xsv --version
  - osm_transit_extractor --version

script:
  - ./extract_lines.sh
  - cat output/lines_from_osm.csv | xsv count

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_DEPLOY_TOKEN
  local_dir: output
  keep-history: true
  on:
    branch: master
